behave: install patchelf to get around RPATH problems
Follow-up to the previous commit, which worked fine for CentOS6 but fell
apart with CentOS7.

Because our vendored Python doesn't contain an RPATH/RUNPATH pointer to
the location of its libpython, trying to execute it directly will result
in failures at link time. The previous commit took the approach that
greenplum_path.sh takes, which is to hardcode an LD_LIBRARY_PATH that
makes up for this bug. This approach works for CentOS6, which is running
Python 2.6 as its system version. On CentOS7, which has Python 2.7, the
LD_LIBRARY_PATH causes the system Python to use the vendored
libpython.so.2.7, and virtualenv fails.

Instead of forcing a cross-linking situation with LD_LIBRARY_PATH, fix
the problem in the vendored Python binary, by using patchelf to set up a
proper RUNPATH. (We originally tried to build our vendored Python with
an RPATH set at compile time, but the only way to do that without
knowing the eventual installation prefix is by setting a relative RPATH
using the `$ORIGIN` construct, and virtualenv is unfortunately
incompatible with that.) We do this on any platforms that provide a
patchelf binary, and do our best to limp along on all others.

Along the way, get rid of the run_behave.yml task, which has been
confusing us for the entirety of this work. CCP jobs now use
run_behave_on_ccp_cluster.yml consistently.

Co-authored-by: Kalen Krempely <kkrempely@pivotal.io>

diff --git a/concourse/tasks/run_behave_on_ccp_cluster.yml b/concourse/tasks/run_behave_on_ccp_cluster.yml
--- a/concourse/tasks/run_behave_on_ccp_cluster.yml
+++ b/concourse/tasks/run_behave_on_ccp_cluster.yml
@@ -9,4 +9,31 @@ run:
   - |
     set -ex
     ccp_src/scripts/setup_ssh_to_cluster.sh
+
+    # Install patchelf. We need to SSH as root, hence the use of
+    # cluster_env_files.
+    ssh -t ccp-$(cat cluster_env_files/terraform/name)-0 "bash -c '
+        # Our Python installation does not run standalone; it requires
+        # LD_LIBRARY_PATH which causes virtualenv to fail (because the system
+        # and vendored libpythons collide). We will try our best to install
+        # patchelf to fix this later, but it is not available on all platforms.
+        set -ex
+        if which zypper > /dev/null; then
+            zypper addrepo https://download.opensuse.org/repositories/devel:tools:building/SLE_12_SP4/devel:tools:building.repo
+            # Note that this will fail on SLES11.
+            if ! zypper --non-interactive --gpg-auto-import-keys install patchelf; then
+                set +x
+                echo \"WARNING: could not install patchelf; virtualenv may fail later\"
+                echo \"WARNING: This is a known issue on SLES11.\"
+                set -x
+            fi
+        elif which yum > /dev/null; then
+            sudo yum install -y patchelf
+        else
+            set +x
+            echo \"ERROR: install_python_hacks() does not support the current platform and should be modified\"
+            exit 1
+        fi
+    '"
+
     ssh -t mdw "$CUSTOM_ENV bash /home/gpadmin/gpdb_src/concourse/scripts/run_behave_test.sh \"$BEHAVE_FLAGS\""
