Import Greenplum source code.

diff --git a/src/tools/pgcvslog b/src/tools/pgcvslog
--- a/src/tools/pgcvslog
+++ b/src/tools/pgcvslog
@@ -1,14 +1,22 @@
 #!/bin/sh
 
-# $PostgreSQL: pgsql/src/tools/pgcvslog,v 1.32 2006/10/08 01:39:59 momjian Exp $
+# $PostgreSQL: pgsql/src/tools/pgcvslog,v 1.39 2007/10/09 02:56:44 momjian Exp $
 
 # This utility is used to generate a compact list of changes
 # for each release, bjm 2000-02-22
 
-# Usage $0 file
+# Usage:  pgcvslog [-d] [-h]
+# -d delete commits that include back branches
+# -h is HTML output
+# "-d" is useful for generating release notes for major releases
+
+# This program basically takes a cvs log, groups it by commit timestamp
+# and line number, then compares adjacent messages.  If they have the same
+# commit message, they are assumed to be part of the same commit and
+# appear as one commit message with multiple file names
 
 # All branches:	
-# cvs log -d '>1999-06-14 00:00:00 GMT' . > log
+# cvs log -d'>1999-06-14 00:00:00 GMT' . > log
 #
 # HEAD:
 # cvs log -d'>2000-05-29 00:00:00 GMT' -b .
@@ -31,10 +39,26 @@
 #	/cvsroot/pgsql/doc/src/FAQ/FAQ.html
 #
 
+HTML="N"
+DEL="N"
 if [ "X$1" = "X-h" ]
 then	HTML="Y"
 	shift
-else	HTML="N"
+fi
+
+if [ "X$1" = "X-d" ]
+then	DEL="Y"
+	shift
+fi
+
+if [ "X$1" = "X-h" ]
+then	HTML="Y"
+	shift
+fi
+
+if [ "$HTML" = "Y" -a "$DEL" = "Y" ]
+then	echo "Cannot use -d and -h together" 1>&2
+	exit 1
 fi
 
 cat "$@" |
@@ -49,6 +73,7 @@ else	cat
 fi |
 
 # mark each line with a datetime and line number, for sorting and merging
+# we are just pre-processing the file at this point
 # We don't print anything from the -- or == line and the date:
 
 awk '	BEGIN	{html="'"$HTML"'"; lineno = 0;}
@@ -87,8 +112,8 @@ awk '	BEGIN	{html="'"$HTML"'"; lineno = 0;}
 		{
 			printf ("%s| %10d|", datetime, lineno++);
 			if (html != "Y")
-				printf ("%s\n", workingfile);
-			else	printf ("<SMALL><FONT COLOR=\"red\">%s</FONT></SMALL>\n", workingfile);
+				printf ("%s%s\n", workingfile, back_branch);
+			else	printf ("<SMALL><FONT COLOR=\"red\">%s%s</FONT></SMALL>\n", workingfile, back_branch);
 
 			# output name of committer
 			# remove semicolon from committers name
@@ -102,27 +127,40 @@ awk '	BEGIN	{html="'"$HTML"'"; lineno = 0;}
 		}
 	}
 
+	# mark back branches
+	$1 == "revision" \
+	{
+		# back branches have +2 periods in revision number
+		if ($2 ~ /\..*\./)
+			back_branch=" <branch>"
+		else	back_branch = ""
+	}
+
 	/* clear working file */
 	$0 ~ /^====*$/	{workingfile=""}' |
 
 sort | cut -d'|' -f3 |
 
 # collect duplicate narratives
+# print file names as we get them, then print narrative when a new 
+# narrative appears
+# have to save two narratives to compare them
 
-awk '   BEGIN   { slot = 0; oldslot=0; save_working = ""; html="'"$HTML"'"}
+awk '   BEGIN   { narr_slot = 0; oldnarr_slot=0; save_working = ""; 
+		  html="'"$HTML"'"}
 	{
 		# We have a filename, so we look at the previous
 		# narrative to see if it is new narrative text.
-		if ($0 ~ /^\// || $0 ~ />\//)
+		if ($0 ~ "^/")
 		{
 			# If there are a different number of narrative
-			# lines, they can not possibly be the same.
-			if (slot != oldslot)
+			# lines, they cannot possibly be the same.
+			if (narr_slot != oldnarr_slot)
 				same = "N";
 			else
 			{
 				same = "Y";
-				for (i=1; i <= slot; i++)
+				for (i=1; i <= narr_slot; i++)
 				{
 					if (oldnarr[i] != narr[i])
 					{
@@ -135,8 +173,8 @@ awk '   BEGIN   { slot = 0; oldslot=0; save_working = ""; html="'"$HTML"'"}
 			# dump out the old narrative if it is new
 			if (same == "N")
 			{
-				if (oldslot)
-					for (i=1; i <= oldslot; i++)
+				if (oldnarr_slot)
+					for (i=1; i <= oldnarr_slot; i++)
 					{
 						print oldnarr[i];
 						if (html == "Y" && 
@@ -146,14 +184,15 @@ awk '   BEGIN   { slot = 0; oldslot=0; save_working = ""; html="'"$HTML"'"}
 					}
 
 				# save the current narrative
-				for (i=1; i <= slot; i++)
+				for (i=1; i <= narr_slot; i++)
 					oldnarr[i] = narr[i];
-				oldslot = slot;
+				oldnarr_slot = narr_slot;
 			}
-			slot = 0;
+			narr_slot = 0;
 
 			# dump out the previous filename
 			print save_working;
+
 			if (html == "Y")
 				print "<BR>";
 
@@ -164,57 +203,58 @@ awk '   BEGIN   { slot = 0; oldslot=0; save_working = ""; html="'"$HTML"'"}
 		# we have a narrative line
 		{
 			# accumulate narrative
-			narr[++slot] = $0;
+			narr[++narr_slot] = $0;
 		}
 	}
-	END	{
-			# If there are a different number of narrative
-			# lines, they can not possibly be the same.
-			if (slot != oldslot)
-				same = "N";
-			else
+	END \
+	{
+		# If there are a different number of narrative
+		# lines, they can not possibly be the same.
+		if (narr_slot != oldnarr_slot)
+			same = "N";
+		else
+		{
+			same = "Y";
+			for (i=1; i <= narr_slot; i++)
 			{
-				same = "Y";
-				for (i=1; i <= slot; i++)
+				if (oldnarr[i] != narr[i])
 				{
-					if (oldnarr[i] != narr[i])
-					{
-						same = "N";
-						break;
-					}
+					same = "N";
+					break;
 				}
 			}
+		}
 
-			# dump out the old narrative if it is new
-			if (same == "N")
-			{
-				if (oldslot)
-					for (i=1; i <= oldslot; i++)
-					{
-						print oldnarr[i];
-						if (html == "Y" && 
-						    oldnarr[i] != "<HR>" &&
-						    oldnarr[i] !~ "^<DIV ")
-							print "<BR>";
-					}
-			}
+		# dump out the old narrative if it is new
+		if (same == "N")
+		{
+			if (oldnarr_slot)
+				for (i=1; i <= oldnarr_slot; i++)
+				{
+					print oldnarr[i];
+					if (html == "Y" && 
+					    oldnarr[i] != "<HR>" &&
+					    oldnarr[i] !~ "^<DIV ")
+						print "<BR>";
+				}
+		}
 
-			# dump out the last filename
-			print save_working;
+		# dump out the last filename
+		print save_working;
 
-			if (html == "Y")
+		if (html == "Y")
+			print "<BR>";
+
+		# dump out the last narrative
+		for (i=1; i <= narr_slot; i++)
+		{
+			print narr[i];
+			if (html == "Y" && 
+			    narr[i] != "<HR>" &&
+			    narr[i] !~ "^<DIV ")
 				print "<BR>";
-
-			# dump out the last narrative
-			for (i=1; i <= slot; i++)
-			{
-				print narr[i];
-				if (html == "Y" && 
-				    narr[i] != "<HR>" &&
-				    narr[i] !~ "^<DIV ")
-					print "<BR>";
-			}
-		}' |
+		}
+	}' |
 
 # add HTML wrapper
 if [ "$HTML" = "Y" ]
@@ -226,5 +266,43 @@ then	echo "<HTML>"
 	cat
 	echo "</BODY>"
 	echo "</HTML>"
+else	cat
+fi |
+
+# if requested, remove any commit that has the "<branch>" text
+if [ "$DEL" = "Y" ]
+then	awk 'BEGIN \
+	{
+		slot = 0;
+	}
+
+	{
+		# new commit?
+		if ($0 ~ "^---$")
+		{
+			skip = "N";
+			for (i=1; i <= slot; i++)
+				if (commit[i] ~ "<branch>")
+					skip = "Y";
+			if (skip == "N")
+				for (i=1; i <= slot; i++)
+					print commit[i];
+			slot = 0;
+		}
+
+		# accumulate commit
+		commit[++slot] = $0;
+	}
+
+	END \
+	{
+		skip = "N";
+		for (i=1; i <= slot; i++)
+			if (commit[i] ~ "<branch>")
+				skip = "Y";
+		if (skip == "N")
+			for (i=1; i <= slot; i++)
+				print commit[i];
+	}'
 else	cat
 fi
